#!bin/bash 
# This script displays number of words and white space in the user input phrase 

echo "Type a phrase:"
read phrase

word_count=$(echo "$phrase" | wc -w)
whitespace_count=$(echo -n "$phrase" | tr -cd '[:space:]' | wc -c)

echo "The number of words is $word_count"
echo "the number of whitespace characters is $whitespace_count"
