#!bin/bash 
# This script displays number of words and white space in the user input phrase 

echo "Type a phrase:"
read phrase

word_count=$(echo "$phrase" | wc -w)
whitespace_count=$(echo -n "$phrase" | tr -cd '[:space:]' | wc -c)

echo "Number of words in the phrase: $word_count"
echo "Number of whitespace characters: $whitespace_count"
